language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
install:
  # Force PHPUnit 7 if $TRAVIS_PHP_VERSION >= '7.1.0'
  - echo "$TRAVIS_PHP_VERSION"
  - |
    if [[ $TRAVIS_PHP_VERSION > '7.1' || $TRAVIS_PHP_VERSION = '7.1' ]]; then
      wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-7.phar;
      chmod 755 ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit;
    fi
before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - phpunit --version
script:
  - phpunit --configuration=./tests/phpunit.xml tests/
